title: Calango de Asa
email: skal@calangodeasa.com
description: >- # this means to ignore newlines until "baseurl:"
  Site da Calango de Asa
baseurl: "/calangodesite" # the subpath of your site, e.g. /blog
url: "http://calangodeasa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  calangodeasa

# Build settings
theme: minima
plugins:
  - jekyll-feed